# -*- coding: utf-8 -*-
"""Constants used by dnsblock."""

DNSBLOCK_BLOCKLIST_PATH = '~/.config/dnsblock/blocklist.txt'
DNSBLOCK_CONFIG_PATH = '~/.config/dnsblock/config.toml'
GEN_COMMENT = '# Generated by dnsblock on %Y-%m-%d at %H:%M:%S\n# https://github.com/swills1/dnsblock\n'
