from struct import unpack
import requests
from dataclasses import dataclass
import concurrent.futures
from typing import Optional
from datetime import datetime
from dnsblock import utils

@dataclass
class BlocklistResponse:
    url: str 
    success: bool
    text: Optional[str] = None

def fetch_blocklist_data(session: requests.Session, url: str, timeout: int) -> BlocklistResponse:
    """Fetch all data from blocklist urls and trap specific errors.

    :param session: Requests session
    :param url: url of blocklist from source file
    :param timeout: number of seconds before Requests timeout
    :return: instance of BlocklistResponse
    """
    try:
        with session.get(url, timeout=timeout) as response:
            return BlocklistResponse(url, True, response.text)
    except requests.exceptions.RequestException as e:
        return BlocklistResponse(url, False, '')


def get_blocklist_data(timeout: int=10, custom_path: str=None, url: str=None):
    """Use threading to process the source list and pull in fetched url data.

    :param timeout: Request timeout in seconds
    :return: results - all raw results returned from each blocklists
    :return: bad_urls - any url that does not have a 200 status code
    :return: good_urls - any url with a 200 status code
    """
    session = requests.Session()
    with concurrent.futures.ThreadPoolExecutor() as executor:
        futures = []
        if custom_path is not None:
            block_host = utils.build_source_list(custom_path)
        elif url is not None:
            block_host = url
        else:
            block_host = utils.build_source_list()
        for blocklist in block_host:
            if not blocklist.startswith('#'):
                futures.append(executor.submit(fetch_blocklist_data, session, blocklist, timeout))
        results = [future.result() for future in concurrent.futures.as_completed(futures)]
        bad_urls = [result.blocklist for result in results if not result.success]
        good_urls = [result.blocklist for result in results if result.success]
    return results, bad_urls, good_urls


def unpack_blocklist_data() -> list[str]:
    """Turn get_blocklist_data results into list - includes IP if present
    
    :return: result_all - raw Requests results converted into a list
    """
    blocklist_data = get_blocklist_data()
    results = (blocklist_data[0])
    result = [obj.text for obj in results]
    for r in result:
        result_all = r.splitlines()
    return result_all


def isolate_hostname() -> list[str]:
    """Isolate hostname when IP present and add just hostnames to list
    
    :return: :list: hostnames
    """
    blocklist_data = unpack_blocklist_data()
    hostnames = []
    for entry in blocklist_data:
        if not entry.startswith('#') and entry.strip() != '':
            hostname = entry.split()
            hostnames.append(hostname[-1])
    return hostnames

#print(isolate_hostname())

def format_dnslist(prefix: str, suffix: str) -> list[str]:
    """Format DNS hostnames in preparation for zone conf file
    
    :param prefix: string before hostname for zone file formatting
    :param suffix: string behind hostname for zone file formatting
    :return: :list: zone_entry_list
    """
    hostnames = isolate_hostname()
    zone_entry_list = []
    for hostname in hostnames:
        zone_entry = hostname #prefix + hostname + suffix
        zone_entry_list.append(zone_entry)
    return zone_entry_list


def build_conf_file(path: str, prefix: str, suffix: str):
    """
    Generate Recursive DNS zone file.

    :param path: path to save zone file
    :param prefix: string before hostname for zone file formatting
    :param suffix: string behind hostname for zone file formatting
    :return: :list: zone_entry_list
    """
    formatted_blocklist = format_dnslist(prefix, suffix)
    dateandtime = datetime.now()
    #date_string = dateandtime.strftime(config.GENERATED_DATETIME_FORMAT)
    with open(path, 'w') as filehandle:
        generatedby_comment = dateandtime.strftime('# Generated by dnsblock on %Y-%m-%d at %H:%M:%S\n# https://github.com/swills1/python-dnsblock\n')
        filehandle.writelines(generatedby_comment)
        filehandle.writelines('server:\n')
        for url in formatted_blocklist:
            block_url = url + '\n'
            filehandle.writelines(block_url)


# placeholder - needs to be rewritten with threading
# urls need to take data from fetch_blocklist_data()
def count_blocklist_entries():
    urls = ['https://v.firebog.net/hosts/Easylist.txt', 'https://v.firebog.net/hosts/Admiral.txt']
    entry_dict = {}
    for url in urls:
        response = requests.get(url)
        entry_count = len(response.text.splitlines())
        entry_dict.update({url: entry_count})
    entry_total = sum(entry_dict.values())
    entry_dict.update({"Total": entry_total})
    return entry_dict
