from struct import unpack
import requests
from dataclasses import dataclass
import concurrent.futures
from typing import Optional
from datetime import datetime
from dnsblock import utils

@dataclass
class url_repsonse:
    url: str 
    success: bool
    text: Optional[str] = None

def fetch_url_data(session, url, timeout):
    """Fetch all data from blocklist urls and trap specific errors.

    :param session: blah
    :param url: blah
    :param timeout: blah
    :return: dataclass url_response
    """
    try:
        with session.get(url, timeout=timeout) as response:
            return url_repsonse(url, True, response.text)
    except requests.exceptions.RequestException as e:
        return url_repsonse(url, False, '')


def get_blocklist_data(timeout=10):
    """Use threading to process the source list and pull in fetched url data.

    :param timeout: Request timeout in seconds
    """
    session = requests.Session()
    with concurrent.futures.ThreadPoolExecutor() as executor:
        futures = []
        for url in utils.build_source_list():
            if not url.startswith('#'):
                futures.append(executor.submit(fetch_url_data, session, url, timeout))
        results = [future.result() for future in concurrent.futures.as_completed(futures)]
        bad_urls = [result.url for result in results if not result.success]
        good_urls = [result.url for result in results if result.success]
    return results, bad_urls, good_urls


def unpack_blocklist_data() -> list[str]:
    """Turn get_blocklist_data results into list - includes IP if present"""
    blocklist_data = get_blocklist_data()
    results = (blocklist_data[0])
    result = [obj.text for obj in results]
    for r in result:
        result_all = r.splitlines()
    return result_all


def isolate_hostname():
    """Isolate hostname when IP present and add hostnames to list"""
    blocklist_data = unpack_blocklist_data()
    hostnames = []
    for entry in blocklist_data:
        if not entry.startswith('#'):
            hostname = entry.split()[1]
            hostnames.append(hostname)
    return hostnames


def format_dnslist(prefix, suffix):
    """Format dns names in preparation for conf file"""
    hostnames = isolate_hostname()
    l = []
    for hostname in hostnames:
        zone_entry = prefix + hostname + suffix
        l.append(zone_entry)
    return l


def build_conf_file(path, prefix, suffix):
    formatted_blocklist = format_dnslist(prefix, suffix)
    dateandtime = datetime.now()
    #date_string = dateandtime.strftime(config.GENERATED_DATETIME_FORMAT)
    with open(path, 'w') as filehandle:
        generatedby_comment = dateandtime.strftime('# Generated by dnsblock on %Y-%m-%d at %H:%M:%S\n# https://github.com/swills1/python-dnsblock\n')
        filehandle.writelines(generatedby_comment)
        filehandle.writelines('server:\n')
        for url in formatted_blocklist:
            block_url = url + '\n'
            filehandle.writelines(block_url)

#build_conf_file('/home/steven/Projects/Python/packages/dnsblock/tmp/blocklist.txt', 'local-zone: "', '" always_refuse')
#local-zone: "m2.ai" always_refuse
